### ISSUE TITLE
运行你的代码，好像产生了问题，确认应该不是我的问题

### ISSUE THREAD

**Issue by jzhou3700** [xu-zhiwei/shu-selfreport#1]
- Traceback (most recent call last):
  File "C:/Users/95279/shu-selfreport/selfreport.py", line 25, in <module>
    main()
  File "C:/Users/95279/shu-selfreport/selfreport.py", line 21, in main
    http_request.automatic_report(config)
  File "C:\Users\95279\shu-selfreport\http_request\report.py", line 170, in automatic_report
    if half_day_report(config, cur_date, is_morning):
  File "C:\Users\95279\shu-selfreport\http_request\report.py", line 148, in half_day_report
    while not report(config, cur_date, is_morning):
  File "C:\Users\95279\shu-selfreport\http_request\report.py", line 88, in report
    view_state = soup.find('input', attrs={'name': '__VIEWSTATE'})['value']
TypeError: 'NoneType' object is not subscriptable

进程已结束,退出代码1

**Comment by xu-zhiwei** [comment]
我这边挂了一两个月了没有问题噢。
你可以检查下配置文件，http_request下的config.txt

student_id：学号
student_password：学号的密码
send_email_id：发件人邮箱地址，如xxxx@qq.com
send_email_password：发件人smtp密码，请到邮箱网站获取
send_email_hostname：发件人主机，如QQ邮箱为smtp.qq.com
receive_email_id：收件人邮箱地址

如果填对了，就可以每日早上八点和晚上八点收到报送成功的邮件了。
建议使用tmux挂载到服务器上。

**Comment by jzhou3700** [comment]
TypeError: 'NoneType' object is not subscriptable
应该不关配置什么事，主要是这里运行错了，我的配置都填进去了
